title: Louis Maréchal
logo: coverphoto.png
#description: text below image
show_downloads: false
theme: jekyll-theme-minimal

email: marechal-louis@hotmail.com"

# Open Graph metadata
og:
  title: "Louis Maréchal - Data Analyst"
  description: "Retrouvez tous mes projets data"
  image: "https://louis-marechal.github.io/coverphoto.png"
  url: "https://louis-marechal.github.io"
